use ecommerce_db;

CREATE TABLE T_SCORE_VARIANTS_CHART_DTLS (
	ID INTEGER NOT NULL,
    SCORE_RANGE VARCHAR(30),
    MIN_SCORE INTEGER,
    MAX_SCORE INTEGER,
    COLOR VARCHAR(20),
    CSS VARCHAR(20),
    PRIMARY KEY (ID)
);

INSERT INTO T_SCORE_VARIANTS_CHART_DTLS values (1, '91 - 100', 91, 100, 'primary', 'table-primary');
INSERT INTO T_SCORE_VARIANTS_CHART_DTLS values (2, '60 - 90', 60, 90, 'primary', 'table-success');
INSERT INTO T_SCORE_VARIANTS_CHART_DTLS values (3, '45 - 59', 45, 59, 'primary', 'table-info');
INSERT INTO T_SCORE_VARIANTS_CHART_DTLS values (4, '35 - 44', 35, 44, 'primary', 'table-warning');
INSERT INTO T_SCORE_VARIANTS_CHART_DTLS values (5, '00 - 34', 00, 34, 'primary', 'table-danger');

SELECT * FROM T_SCORE_VARIANTS_CHART_DTLS;
DROP TABLE T_SCORE_VARIANTS_CHART_DTLS;
COMMIT

CREATE TABLE T_SCORE_CARD_REPORT_DTLS (
	STUDENT_ID INTEGER NOT NULL,
    STUDENT_NAME VARCHAR(20),
    MATHEMATICS INTEGER,
    SCIENCE INTEGER,
    ENGLISH INTEGER,
    HINDI INTEGER,
    SOCIAL_SCIENCE INTEGER,
    RESULT VARCHAR(10),
    PRIMARY KEY (STUDENT_ID)
);

INSERT INTO T_SCORE_CARD_REPORT_DTLS values (101, 'Sanjay Kumar', 99, 95, 13, 88, 45, 'Fail');
INSERT INTO T_SCORE_CARD_REPORT_DTLS values (102, 'Rajni Bala', 78, 88, 77, 55, 69, 'Pass');
INSERT INTO T_SCORE_CARD_REPORT_DTLS values (103, 'Sangram Nayak', 45, 51, 65, 88, 61, 'Pass');
INSERT INTO T_SCORE_CARD_REPORT_DTLS values (104, 'Janhabi Nayak', 22, 40, 23, 86, 98, 'Pass');
INSERT INTO T_SCORE_CARD_REPORT_DTLS values (105, 'Lucky Nayak', 75, 17, 13, 32, 81, 'Pass');

SELECT * FROM T_SCORE_CARD_REPORT_DTLS;
DROP TABLE T_SCORE_CARD_REPORT_DTLS;
